### ISSUE TITLE
Source map files

### ISSUE THREAD

**Issue by newhen** [waf/anki-json#3]
Where do I get a source map file like you have

**Comment by waf** [comment]
Hi @newhen, sorry for the delay, I missed this notification.

The source map file is up to you to design, if you need it. Because the input card data is an array of json objects that looks something like this:

```json
[
    {
        "rank":"1",
        "source":"AUA Reader AUA Chapter 01",
        "thai": "ดี",
        "english":"To be good."
   },
   {
        "rank":"1",
        "source":"AUA Reader AUA Chapter 02",
        "thai": "หนึ่ง",
        "english":"One, a."
   },
]
```

If you import this file, it would not have any categories in the resulting Anki deck (because it's a flat array of cards). If you want categories (in this case, a category for each chapter), you would design a source map like this:

```json
{
    "AUA Reader AUA Chapter 01": {
        "source": "AUA Lessons::Chapter 01"
    },
    "AUA Reader AUA Chapter 02": {
        "source": "AUA Lessons::Chapter 02"
    }
}
```

This would map the "source" field to an Anki category. The end result is a structured deck like the following:
<br />

<img src="https://user-images.githubusercontent.com/97195/40399199-26284bc6-5e66-11e8-9741-847ad8880f21.png" width="300" />
